#!/usr/bin/env bash
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function do_link(){
    if [ -e $2 ] || [ -d $2 ]; then
        echo "$2 already exists, skipping"
    else
        echo "ln -s $1 $2"
        ln -s $1 $2
    fi
}

function link_to_home(){
    do_link "$BASE_DIR/$1" "$HOME/.$1"
}

function create_dir(){
	if [ ! -e $1 ]
	then
		mkdir $1
	fi
}

link_to_home ackrc
link_to_home gitconfig
link_to_home gitignore_global
link_to_home tmux.conf
link_to_home vim
link_to_home vimrc

do_link "$BASE_DIR/ssh_config" "$HOME/.ssh/config"

create_dir ~/.config
create_dir ~/.config/fish
do_link "$BASE_DIR/config.fish" ~/config/fish/config.fish








